import { Alert } from "@material-tailwind/react";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl mt-3 font-bold underline">Hello world!</h1>
      <Alert>A simple alert for showing message.</Alert>
    </div>
  );
}
